project_id = "wfywmkdqyuucxftpvmfj"

[functions.analyze-codebase]
verify_jwt = false

[functions.code-chat]
verify_jwt = false

[functions.analyze-github-code]
verify_jwt = false

[functions.suggest-features]
verify_jwt = false

[functions.generate-prompt]
verify_jwt = false
