project_id = "wfywmkdqyuucxftpvmfj"

[functions.analyze-codebase]
verify_jwt = false

[functions.code-chat]
verify_jwt = false

[functions.analyze-github-code]
verify_jwt = false

[functions.github-repos]
verify_jwt = true
